version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    target-branch: "develop"
    
    # temporarily disabled until 2024
    open-pull-requests-limit: 30

    commit-message:
      prefix: "fix"
      prefix-development: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    
    # temporarily disabled until 2024
    open-pull-requests-limit: 0
    
    commit-message:
      prefix: "ci"
